spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/husseinmuhammadi/microservices-configuration.git
          username:
          password:
          default-label: main
          clone-on-start: true

--- # local
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8071

--- # dev
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8071

--- # stage
spring:
  config:
    activate:
      on-profile: stage
server:
  port: 80

--- # prod
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 80
