spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: users
          uri: http://localhost:9001/
          predicates:
            - Path=/users/index
        - id: account
          uri: http://localhost:9002/
          predicates:
            - Path=/account/**
#        - id: users-index
#          uri: lb://users-ws
#          predicates:
#            - Path=/users/index
#            - Method=GET
#          filters:
#            - RemoveRequestHearder=Cookie

server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/


