spring:
  application:
    name: api-gateway
  profiles:
    active: ${spring.active.profiles}
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: users-status-check
          uri: lb://users
          predicates:
            - Path=/users-ws/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
        - id: users-save
          uri: lb://users
          predicates:
            - Path=/users-ws/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>/?.*), /$\{segment}

#        - id: account
#          uri: lb://account-management-ws
#          predicates:
#            - Path=/account/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka/

---

spring:
  config:
    activate:
      on-profile: stage

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:80/eureka/

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:80/eureka/
