spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: users-status-check
          uri: lb://users
          predicates:
            - Path=/users-ws/users/index
            - Method=GET
          filters:
            - RewritePath=/users-ws/users/index, /users/index
            - AuthorizationHeaderFilter


#        - id: users-status-check
#          uri: lb://users
#          predicates:
#            - Path=/users-ws/**
#            - Method=GET
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
        - id: users-save
          uri: lb://users
          predicates:
            - Path=/users-ws/api/v1/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/api/v1/users, /api/v1/users

        - id: get-all-users
          uri: lb://users
          predicates:
            - Path=/users-ws/api/v1/users
            - Method=GET
          filters:
            - RewritePath=/users-ws/api/v1/users, /api/v1/users

        - id: login
          uri: lb://auth-service
          predicates:
            - Path=/login
            - Method=POST

#        - id: account
#          uri: lb://account-management-ws
#          predicates:
#            - Path=/account/**

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,httptrace"
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

token:
  secret: secret

---

spring:
  config:
    activate:
      on-profile: stage

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka/

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:80/eureka/
