---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
token:
  secret: secret
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,httptrace"
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
---
spring:
  config:
    activate:
      on-profile: stage
server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka/

token:
  secret: secret
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:80/eureka/
