spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: users
          uri: lb://users-ws
          predicates:
            - Path=/users/index
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
        - id: account
          uri: lb://account-management-ws
          predicates:
            - Path=/account/**

server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/


