spring:
  application:
    name: auth-service

management:
  endpoints:
    web:
      exposure:
        include: "info,health,mappings"

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(18971){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

--- # local

spring:
  config:
    activate:
      on-profile: local
server:
  port: 8002
eureka:
  client:
    enabled: false

--- # dev

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8002
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

--- # stage

spring:
  config:
    activate:
      on-profile: stage
server:
  port: 0

--- # prod

spring:
  config:
    activate:
      on-profile: prod
server:
  port: 0
