version: "3.8"
services:
  users-service:
    build:
      context: user
      dockerfile: ./Dockerfile
    image: digilab/users-microservice
    container_name: users-microservice
    ports:
      - 8001:80
    networks:
      - digilinq-network
networks:
  digilinq-network:
    name: digilinq
    external: true