version: "3.8"
services:
  users-service:
    build:
      context: user
      dockerfile: Dockerfile
    image: digilab/platform/users-microservice
    container_name: users-microservice
    networks:
      - digilinq-network
  auth-service:
    build:
      context: auth
      dockerfile: Dockerfile
    image: digilab/platform/auth-microservice
    container_name: auth-microservice
    networks:
      - digilinq-network
networks:
  digilinq-network:
    name: digilinq
    external: true