spring:
  application:
    name: zuul

  profiles:
    active: ${spring.active.profiles}

---

spring:
  profiles: local

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: dev

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka/

---

spring:
  profiles: stage

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka/
