spring:
  application:
    name: eurika-discovery

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8761

---

spring:
  config:
    activate:
      on-profile: stage

server:
  port: 8761

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8761

