openapi: 3.0.3
info:
  title: Auth Microservice
  version: 1.0.0
paths:
  /info:
    get:
      description: ss
      responses:
        200:
          description: dd
          content:
            application/json:
              schema:
                type: string
              
components:
  schemas:
    LoginRequest:
      type: object
      required: 
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    LoginByEmailRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string

          
