version: '3.8'

services:
  eureka-discovery-service:
    build:
      context: ..
      dockerfile: infrastructure/eureka-discovery-service/Dockerfile
      args:
        PROFILE: dev
    image: digilab/eureka-discovery-service
    container_name: eureka-discovery-service
    ports:
      - 8761:8761
    networks:
      - digilinq-network
  zuul-api-gateway:
    build:
      context: ..
      dockerfile: infrastructure/zuul-api-gateway/Dockerfile
      args:
        PROFILE: dev
    image: digilab/zuul-api-gateway
    container_name: zuul-api-gateway
    depends_on:
      - eureka-discovery-service
      - spring-cloud-config-server
    ports:
      - 8081:80
    networks:
      - digilinq-network
  spring-cloud-api-gateway:
    build:
      context: spring-cloud-api-gateway
      dockerfile: Dockerfile
      args:
        PROFILE: stage
    image: digilab/spring-cloud-api-gateway
    container_name: spring-cloud-api-gateway
    depends_on:
      - eureka-discovery-service
      - spring-cloud-config-server
    ports:
      - 8080:80
    networks:
      - digilinq-network
  spring-cloud-config-server:
    build:
      context: ..
      dockerfile: infrastructure/spring-cloud-config-server/Dockerfile
      args:
        PROFILE: dev
    image: digilab/spring-cloud-config-server
    container_name: spring-cloud-config-server
    ports:
      - 8071:80
    networks:
      - digilinq-network
  postgres:
    image: postgres:13.2
    container_name: postgres
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 15432:5432
    networks:
      - digilinq-network
networks:
  digilinq-network:
    name: digilinq
