version: '3.8'

services:
  eureka-disconvery-service:
    build:
      context: ./eurika-discovery-service
      dockerfile: ./Dockerfile
    image: eureka-discovery-service
    container_name: eureka-discovery-service
    depends_on:
      - postgres
    ports:
      - 8761:8761
    networks:
      - digiboy-network
  postgres:
    image: postgres:13.2
    container_name: postgres
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 55432:5432
    networks:
      - digiboy-network
networks:
  digiboy-network:
    name: digiboy
